# Generated by Django 5.0.3 on 2024-04-15 18:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Desarrolladoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Desarrolladoras",
            },
        ),
        migrations.CreateModel(
            name="Generos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Generos",
            },
        ),
        migrations.CreateModel(
            name="Juegos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("fecha_Lanzamiento", models.DateField()),
                ("resumen", models.TextField()),
                ("valoracion", models.FloatField()),
                ("numero_Partidas", models.IntegerField()),
                ("numero_jugadores", models.IntegerField()),
                ("comprado_no_jugado", models.IntegerField()),
                ("menciones_listas", models.IntegerField()),
                ("listas_de_deseos", models.IntegerField()),
                ("reseñas", models.IntegerField()),
            ],
            options={
                "db_table": "Juegos",
            },
        ),
        migrations.CreateModel(
            name="Plataformas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Plataformas",
            },
        ),
        migrations.CreateModel(
            name="ImagenesJuegos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen_game",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image_game"
                    ),
                ),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Juegos.juegos",
                    ),
                ),
            ],
            options={
                "db_table": "ImagenesJuegos",
            },
        ),
        migrations.CreateModel(
            name="JuegosXDesarrolladora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desarrolladora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Juegos.desarrolladoras",
                    ),
                ),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Juegos.juegos"
                    ),
                ),
            ],
            options={
                "db_table": "JuegosXDesarrolladora",
            },
        ),
        migrations.AddField(
            model_name="juegos",
            name="desarrolladora",
            field=models.ManyToManyField(
                blank=True,
                related_name="juegos_desarrolladora",
                through="Juegos.JuegosXDesarrolladora",
                to="Juegos.desarrolladoras",
            ),
        ),
        migrations.CreateModel(
            name="JuegosXGenero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Juegos.generos"
                    ),
                ),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Juegos.juegos"
                    ),
                ),
            ],
            options={
                "db_table": "JuegosXGenero",
            },
        ),
        migrations.AddField(
            model_name="juegos",
            name="generos",
            field=models.ManyToManyField(
                blank=True,
                related_name="juegos_generos",
                through="Juegos.JuegosXGenero",
                to="Juegos.generos",
            ),
        ),
        migrations.CreateModel(
            name="JuegosXPlataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Juegos.juegos"
                    ),
                ),
                (
                    "plataforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Juegos.plataformas",
                    ),
                ),
            ],
            options={
                "db_table": "JuegosXPlataforma",
            },
        ),
        migrations.AddField(
            model_name="juegos",
            name="plataformas",
            field=models.ManyToManyField(
                blank=True,
                related_name="juegos_plataformas",
                through="Juegos.JuegosXPlataforma",
                to="Juegos.plataformas",
            ),
        ),
    ]
