# Generated by Django 5.0.3 on 2024-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrolladoras',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
