# Generated by Django 5.0.3 on 2024-04-10 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Juegos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagenesjuegos",
            name="name",
        ),
        migrations.AlterModelTable(
            name="desarrolladoras",
            table="Desarrolladoras",
        ),
        migrations.AlterModelTable(
            name="generos",
            table="Generos",
        ),
        migrations.AlterModelTable(
            name="imagenesjuegos",
            table="ImagenesJuegos",
        ),
        migrations.AlterModelTable(
            name="juegos",
            table="Juegos",
        ),
        migrations.AlterModelTable(
            name="plataformas",
            table="Plataformas",
        ),
    ]
