# Generated by Django 5.0.3 on 2024-04-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0002_alter_desarrolladoras_nombre_alter_juegos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='fecha_Lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
