# Generated by Django 5.0.3 on 2024-05-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0009_alter_imagenesjuegos_imagen_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenesjuegos',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='imagenesjuegos',
            name='imagen_game',
            field=models.URLField(blank=True, null=True),
        ),
    ]
