# Generated by Django 5.0.3 on 2024-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocatalogo',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
