# Generated by Django 5.0.3 on 2024-04-10 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuariocatalogo",
            options={},
        ),
        migrations.AlterModelTable(
            name="usuariocatalogo",
            table="UsuarioCatalogo",
        ),
    ]
