# Generated by Django 5.0.3 on 2024-05-06 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_emailverificationcode_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocatalogo',
            name='image_profile',
            field=cloudinary.models.CloudinaryField(blank=True, default='CatalogoJuegos/Portadas/tt6wwojkibqqjtlu3o1t', max_length=255, null=True, verbose_name='image_profile'),
        ),
    ]
